name: Stack
description: Build, test, and lint a stack-based Haskell project
inputs:
  working-directory:
    description: "Working directory for run commands"
    required: true
    default: .
  stack-yaml:
    description: "Override stack.yaml"
    required: true
    default: stack.yaml
outputs: {}
runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack setup
          stack install --copy-compiler-tool hlint weeder

    - name: Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build --dependencies-only --test --no-run-tests

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build --fast --pedantic --test --no-run-tests

    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build --fast --pedantic --test

    - name: Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack exec hlint .
          stack exec weeder
