name: Stack
description: Build, test, and lint a stack-based Haskell project
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: |
          stack setup
          stack install --copy-compiler-tool hlint weeder

    - name: Dependencies
      shell: bash
      run: |
          stack --no-terminal build --dependencies-only --test --no-run-tests

    - name: Build
      shell: bash
      run: |
          stack --no-terminal build --fast --pedantic --test --no-run-tests

    - name: Test
      shell: bash
      run: |
          stack --no-terminal build --fast --pedantic --test

    - name: Lint
      shell: bash
      run: |
          stack exec hlint .
          stack exec weeder
