name: Stack
description: Build, test, and lint a stack-based Haskell project
inputs:
  working-directory:
    description: "Working directory for run commands"
    required: true
    default: .
outputs: {}
runs:
  using: composite
  steps:
    - name: Setup
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack setup
          stack install --copy-compiler-tool hlint weeder

    - name: Dependencies
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal build --dependencies-only --test --no-run-tests

    - name: Build
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal build --fast --pedantic --test --no-run-tests

    - name: Test
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal build --fast --pedantic --test

    - name: Lint
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack exec hlint .
          stack exec weeder
